"""Expand models with RBAC roles and student external profiles

Revision ID: 65c0bc959518
Revises: 
Create Date: 2026-09-30 12:20:54.094000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c0bc959518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_career_twins', schema=None) as batch_op:
        batch_op.alter_column('academic_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('skill_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('project_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('interview_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('market_competitiveness',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Premium Product Companies'"))
        batch_op.alter_column('metadata_json_str',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('ai_interview_sessions', schema=None) as batch_op:
        batch_op.alter_column('feedback_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('ai_resume_analyses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ai_resume_analyses_job_id', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ai_roadmaps', schema=None) as batch_op:
        batch_op.alter_column('progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_roadmaps', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('ai_resume_analyses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_resume_analyses_job_id', type_='foreignkey')

    with op.batch_alter_table('ai_interview_sessions', schema=None) as batch_op:
        batch_op.alter_column('feedback_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('ai_career_twins', schema=None) as batch_op:
        batch_op.alter_column('metadata_json_str',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('market_competitiveness',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Premium Product Companies'"))
        batch_op.alter_column('interview_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('project_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('skill_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('academic_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))

    # ### end Alembic commands ###
